version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.26
    container_name: etcd
    ports:
      - 2379:2379
    command: etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379
    restart: unless-stopped
